services:
  mysql:
    container_name: database
    image: ghcr.io/maxones25/studien_generator_app/test-database:latest
    command:
      [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
      ]
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=studien_generator_app
    ports:
      - 3306:3306
    networks:
      - study-app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      interval: 5s
      timeout: 5s
      retries: 10
  
  test-setup:
    container_name: test-setup
    image: ghcr.io/maxones25/studien_generator_app/test-setup:latest
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=studien_generator_app
    command: sh -c "npm run db:migration:run && npm run db:seed:run && touch /usr/src/app/.healthcheck"
    healthcheck:
      test: ["CMD-SHELL", "[ -f /usr/src/app/.healthcheck ] || exit 1"]
      interval: 30s
      timeout: 30s
      retries: 3
    networks:
      - study-app-network

  admin-backend:
    container_name: admin-backend
    image: ghcr.io/maxones25/studien_generator_app/admin-backend:latest
    depends_on:
      test-setup:
        condition: service_healthy
    ports:
      - 8000:8000
    environment:
      - DB_HOST=mysql
    networks:
      - study-app-network
    healthcheck:
      test:
        ["CMD", "curl", "-f", "http://127.0.0.1:8000/health"]
      interval: 5s
      timeout: 5s
      retries: 10

  admin-frontend:
    container_name: admin-frontend
    image: ghcr.io/maxones25/studien_generator_app/admin-frontend:latest
    depends_on:
      admin-backend:
        condition: service_healthy
    ports:
      - 3000:3000
    networks:
      - study-app-network

networks:
  study-app-network:
