services:
  mysql:
    container_name: database
    image: mysql
    command:
      [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
      ]
    volumes:
      - ./mysql/data:/var/lib/mysql
      - ./mysql/schema.sql:/docker-entrypoint-initdb.d/0-schema.sql
      - ./mysql/seed/test-seed.sql:/docker-entrypoint-initdb.d/1-seed.sql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=studien_generator_app
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      interval: 5s
      timeout: 5s
      retries: 10