services:
  mysql:
    container_name: database
    image: ghcr.io/maxones25/studien_generator_app/test-database:latest
    command:
      [
        "--character-set-server=utf8mb4",
        "--collation-server=utf8mb4_unicode_ci",
      ]
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=studien_generator_app
    ports:
      - 3306:3306
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "127.0.0.1"]
      start_period: 30s
      interval: 10s
      timeout: 30s
      retries: 3
