services:
    mysql:
      container_name: database
      image: mysql
      command:
        [
          "--character-set-server=utf8mb4",
          "--collation-server=utf8mb4_unicode_ci",
        ]
      volumes:
        - ./mysql/data:/var/lib/mysql
        - ./mysql/schema.sql:/docker-entrypoint-initdb.d/0-schema.sql
        - ./mysql/seed/dev-seed.sql:/docker-entrypoint-initdb.d/1-seed.sql
      environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=studien_generator_app
      ports:
        - 3306:3306
      healthcheck:
        test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
        interval: 5s
        timeout: 5s
        retries: 10

    phpmyadmin:
      container_name: phpmyadmin
      image: phpmyadmin/phpmyadmin
      ports:
        - 8080:80
      environment:
        - PMA_HOST=mysql
        - PMA_USER=root
        - PMA_PASSWORD=root
      healthcheck:
        test: ["CMD", "curl", "--fail", "--silent", "http://localhost:8080"]
        interval: 5s
        timeout: 5s
        retries: 10