name: "[App] Release"

on:
  push:
    branches:
      - main

env: 
  TEST: true

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      pipeline: ${{ steps.filter.outputs.pipeline }}
      database: ${{ steps.filter.outputs.database }}
      admin_backend: ${{ steps.filter.outputs.admin_backend }}
      admin_backend_tests: ${{ steps.filter.outputs.admin_backend_tests }}
      admin_frontend: ${{ steps.filter.outputs.admin_frontend }}
      study_backend: ${{ steps.filter.outputs.study_backend }}
      study_backend_tests: ${{ steps.filter.outputs.study_backend_tests }}
      study_frontend: ${{ steps.filter.outputs.study_frontend }}
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            pipeline:
              - '.github/workflows/**'
            database:
              - 'backend/migrations/**'
              - 'mysql/schema.sql'
              - 'mysql/seed/**'
            admin_backend:
              - 'backend/apps/admin/src/**'
              - 'backend/migrations/**'
              - 'backend/libs/entities/**'
              - 'backend/libs/shared/**'
            admin_backend_tests:
              - 'backend/apps/admin/test/**'
              - 'backend/libs/test/**'
            admin_frontend:
              - 'frontend/admin-app/**'
            admin_frontend_tests:
              - 'tests/cypress/e2e/admin-app/**'
            study_backend:
              - 'backend/apps/study/src/**'
              - 'backend/migrations/**'
              - 'backend/libs/entities/**'
              - 'backend/libs/shared/**'
            study_backend_tests:
              - 'backend/apps/study/test/**'
              - 'backend/libs/test/**'
            study_frontend:
              - 'frontend/study-app/**'
            study_frontend_tests:
              - 'tests/cypress/e2e/study-app/**'

  build-database-container:
    runs-on: ubuntu-latest
    needs: changes
    steps:
      - name: Get latest code
        if: needs.changes.outputs.database == 'true'
        uses: actions/checkout@v2

      - name: Log into GitHub Container Registry
        if: needs.changes.outputs.database == 'true'
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and Push admin-frontend container
        if: needs.changes.outputs.database == 'true'
        run: |
          docker build ./mysql -t ghcr.io/${{ github.repository }}/test-database:latest -f ./mysql/test.dockerfile
          docker push ghcr.io/${{ github.repository }}/test-database:latest

  build-admin-frontend-container:
    runs-on: ubuntu-latest
    needs: changes
    steps:
      - name: Get latest code
        if: needs.changes.outputs.admin_frontend == 'true'
        uses: actions/checkout@v2

      - name: Log into GitHub Container Registry
        if: needs.changes.outputs.admin_frontend == 'true'
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and Push admin-frontend container
        if: needs.changes.outputs.admin_frontend == 'true'
        run: |
          docker build ./frontend/admin-app -t ghcr.io/${{ github.repository }}/admin-frontend:latest -f ./frontend/admin-app/dockerfile
          docker push ghcr.io/${{ github.repository }}/admin-frontend:latest

  build-admin-backend-container:
    runs-on: ubuntu-latest
    needs: changes
    steps:
      - name: Get latest code
        if: needs.changes.outputs.admin_backend == 'true'
        uses: actions/checkout@v2

      - name: Log into GitHub Container Registry
        if: needs.changes.outputs.admin_backend == 'true'
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and Push admin-frontend container
        if: needs.changes.outputs.admin_backend == 'true'
        run: |
          docker build ./backend -t ghcr.io/${{ github.repository }}/admin-backend:latest -f ./backend/admin.dockerfile
          docker push ghcr.io/${{ github.repository }}/admin-backend:latest

  build-study-frontend-container:
    runs-on: ubuntu-latest
    needs: changes
    steps:
      - name: Get latest code
        if: needs.changes.outputs.study_frontend == 'true'
        uses: actions/checkout@v2

      - name: Log into GitHub Container Registry
        if: needs.changes.outputs.study_frontend == 'true'
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and Push study-frontend container
        if: needs.changes.outputs.study_frontend == 'true'
        run: |
          docker build ./frontend/study-app -t ghcr.io/${{ github.repository }}/study-frontend:latest -f ./frontend/study-app/dockerfile
          docker push ghcr.io/${{ github.repository }}/study-frontend:latest

  build-study-backend-container:
    runs-on: ubuntu-latest
    needs: changes
    steps:
      - name: Get latest code
        if: needs.changes.outputs.study_backend == 'true'
        uses: actions/checkout@v2

      - name: Log into GitHub Container Registry
        if: needs.changes.outputs.study_backend == 'true'
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build and Push admin-frontend container
        if: needs.changes.outputs.study_backend == 'true'
        run: |
          docker build ./backend -t ghcr.io/${{ github.repository }}/study-backend:latest -f ./backend/study.dockerfile
          docker push ghcr.io/${{ github.repository }}/study-backend:latest

  admin-backend-tests:
    runs-on: ubuntu-latest
    needs: [changes, build-database-container, build-admin-backend-container]
    if: |
      needs.changes.outputs.pipeline == 'true' ||
      needs.changes.outputs.admin_backend == 'true' ||
      needs.changes.outputs.admin_backend_tests == 'true'
    steps:
      - name: Get latest code
        uses: actions/checkout@v2

      - name: Cache npm dependencies
        uses: actions/cache@v2
        with:
          path: ./backend/node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('./backend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install packages
        working-directory: ./backend
        run: npm ci

      - name: Start database containers
        run: docker-compose -f database-docker-compose.yaml up -d

      - name: Wait for MySQL
        run: sleep 10s

      - name: Run Migrations
        working-directory: ./backend
        run: npm run db:migration:run

      - name: Run integration tests
        working-directory: ./backend
        env:
          NODE_OPTIONS: "--max_old_space_size=4096"
        run:
          npm run test:admin:integration

  study-backend-tests:
    runs-on: ubuntu-latest
    needs: [changes, build-database-container, build-study-backend-container]
    if: |
      needs.changes.outputs.pipeline == 'true' ||
      needs.changes.outputs.study_backend == 'true' ||
      needs.changes.outputs.study_backend_tests == 'true'
    steps:
      - name: Get latest code
        uses: actions/checkout@v2

      - name: Cache npm dependencies
        uses: actions/cache@v2
        with:
          path: ./backend/node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('./backend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install packages
        working-directory: ./backend
        run: npm ci

      - name: Start database containers
        run: |
          docker-compose -f database-docker-compose.yaml build
          docker-compose -f database-docker-compose.yaml up -d

      - name: Wait for MySQL
        run: sleep 10s

      - name: Run Migrations
        working-directory: ./backend
        run: npm run db:migration:run

      - name: Run integration tests
        working-directory: ./backend
        run: npm run test:study:integration

  admin-frontend-tests:
    runs-on: ubuntu-latest
    needs:
      [changes, build-admin-frontend-container, build-admin-backend-container]
    if: |
      needs.changes.outputs.pipeline == 'true' ||
      needs.changes.outputs.admin_backend == 'true' ||
      needs.changes.outputs.admin_frontend == 'true' ||
      needs.changes.outputs.admin_frontend_tests == 'true'
    steps:
      - name: Get latest code
        uses: actions/checkout@v2

      - name: Cache npm dependencies
        uses: actions/cache@v2
        with:
          path: ./tests/cypress/node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('./tests/cypress/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install packages
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: ./tests/cypress
        run: npm ci

      - name: Build admin-backend containers
        run: |
          docker-compose -f admin-docker-compose.yaml build

      - name: Start admin-backend containers
        run: |
          docker-compose -f admin-docker-compose.yaml up -d

      - name: Run end to end tests
        working-directory: ./tests/cypress
        run: npm run test:admin

  study-frontend-tests:
    runs-on: ubuntu-latest
    needs:
      [changes, build-study-frontend-container, build-study-backend-container]
    if: |
      needs.changes.outputs.pipeline == 'true' ||
      needs.changes.outputs.study_backend == 'true' ||
      needs.changes.outputs.study_frontend == 'true' ||
      needs.changes.outputs.study_frontend_tests == 'true'
    steps:
      - name: Get latest code
        uses: actions/checkout@v2

      - name: Cache npm dependencies
        uses: actions/cache@v2
        with:
          path: ./tests/cypress/node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('./tests/cypress/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install packages
        if: steps.cache.outputs.cache-hit != 'true'
        working-directory: ./tests/cypress
        run: npm ci

      - name: Build study-backend containers
        run: |
          docker-compose -f study-docker-compose.yaml build

      - name: Start study-backend containers
        run: |
          docker-compose -f study-docker-compose.yaml up -d

      - name: Wait for 30 seconds
        run: sleep 30

      - name: Run end to end tests
        working-directory: ./tests/cypress
        run: npm run test:study
