name: "[App] Release"

on:
  push:
    branches:
      - main

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      admin_backend: ${{ steps.filter.outputs.admin_backend }}
      admin_frontend: ${{ steps.filter.outputs.admin_frontend }}
      study: ${{ steps.filter.outputs.study }}
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: filter
        with:
          filters: |
            admin_backend:
              - 'backend/apps/admin/**'
              - 'backend/libs/**'
            admin_frontend:
              - 'frontend/admin-app/**'
            study:
              - 'backend/apps/study/**'
              - 'backend/libs/**'
              - 'frontend/study-app/**'

  admin-backend-tests:
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.admin_backend == 'true'
    steps:
      - name: Get latest code
        uses: actions/checkout@v2

      - name: Cache npm dependencies
        uses: actions/cache@v2
        with:
          path: ./backend/node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('./backend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install packages
        working-directory: ./backend
        run: npm ci

      - name: Start database containers
        run: |
          docker-compose -f database-docker-compose.yaml build
          docker-compose -f database-docker-compose.yaml up -d

      - name: Run integration tests
        working-directory: ./backend
        run: npm run test:admin:integration

  study-backend-tests:
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.study == 'true'
    steps:
      - name: Get latest code
        uses: actions/checkout@v2

      - name: Cache npm dependencies
        uses: actions/cache@v2
        with:
          path: ./backend/node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('./backend/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install packages
        working-directory: ./backend
        run: npm ci

      - name: Start database containers
        run: |
          docker-compose -f database-docker-compose.yaml build
          docker-compose -f database-docker-compose.yaml up -d

      - name: Run integration tests
        working-directory: ./backend
        run: npm run test:study:integration

  admin-frontend-tests:
    runs-on: ubuntu-latest
    needs: changes
    if: needs.changes.outputs.admin_backend == 'true' || needs.changes.outputs.admin_frontend == 'true'
    steps:
      - name: Get latest code
        uses: actions/checkout@v2

      - name: Cache npm dependencies
        uses: actions/cache@v2
        with:
          path: ./tests/node_modules
          key: ${{ runner.os }}-npm-${{ hashFiles('./tests/cypress/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-npm-

      - name: Install packages
        working-directory: ./tests/cypress
        run: npm ci

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Start admin containers
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          tags: user/app:latest
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Start admin containers
        run: |
          docker-compose -f admin-docker-compose.yaml build
          docker-compose -f admin-docker-compose.yaml up -d

      - name: Run end to end tests
        working-directory: ./tests/cypress
        run: npm run test:admin-app
